services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bridge

  postgres-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - bridge

  user-service:
    build:
      context: .
      dockerfile: ./Dockerfile-user
    depends_on:
      - postgres
      - postgres-service
    ports:
      - "8081:8081"
    networks:
      - bridge

  book-service:
    build:
      context: .
      dockerfile: ./Dockerfile-book
    depends_on:
      - postgres
      - postgres-service
    ports:
      - "8082:8082"
    networks:
      - bridge

  immudb:
    ports:
      - '3322:3322'
    container_name: immudb
    environment:
      - IMMUDB_ADDRESS=127.0.0.1
      - IMMUDB_AUTH=false
    image: 'codenotary/immudb:latest'
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  postgres-data:
