version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - vertx-network

  vertx-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    networks:
      - vertx-network

networks:
  vertx-network:
    driver: bridge
