name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        continue-on-error: true

      - name: List files in wiki directory before copying
        run: ls -la wiki

      - name: Remove Old Documentation from Wiki
        run: |
          echo "Removing old documentation..."
          rm -rf wiki/*

      - name: Copy Markdown Files to Wiki
        run: |
          echo "Copying Markdown files..."
          cp -r docs/*.md wiki/
          ls -la wiki  # List files to verify copying

      - name: Set Home Page
        run: |
          echo "Setting home page..."
          if [ -f "wiki/Explanations.md" ]; then
            echo "Home page set to Explanations.md"
            sed -i 's|# Home|# Home\n\n[Explanations](Explanations.md)|' wiki/_Sidebar.md || echo "Sidebar file not found. No changes made."
          else
            echo "Explanations.md not found. No changes made."
          fi

      - name: Commit and Push Changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki pages from main repository" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: List files in wiki directory after push
        run: ls -la wiki
