name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Swagger UI and Swagger CLI
        run: |
          npm install -g swagger-cli
          npm install swagger-ui-dist

      - name: Verify Swagger UI Installation
        run: ls -la node_modules/swagger-ui-dist

      - name: Generate API Documentation
        run: |
          mkdir -p docs/swagger-ui
          cp -r node_modules/swagger-ui-dist/* docs/swagger-ui/
          swagger-cli bundle docs/openapi.yaml --outfile docs/swagger-ui/openapi.json --type json
          echo '<!DOCTYPE html><html><head><title>API Documentation</title><link rel="stylesheet" type="text/css" href="swagger-ui.css" /></head><body><div id="swagger-ui"></div><script src="swagger-ui-bundle.js"></script><script src="swagger-ui-standalone-preset.js"></script><script>window.onload = function() { window.ui = SwaggerUIBundle({ url: "openapi.json", dom_id: "#swagger-ui", presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset], layout: "StandaloneLayout" }); }</script></body></html>' > docs/swagger-ui/index.html

      - name: List files in docs directory
        run: ls -la docs/swagger-ui

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        continue-on-error: true

      - name: List files in wiki directory before copying
        run: ls -la wiki

      - name: Copy Documentation to Wiki
        run: |
          echo "Copying files..."
          cp -r docs/swagger-ui/* wiki/
          ls -la wiki  # List files to verify copying

      - name: Verify Paths and Generate API Documentation Markdown
        run: |
          echo "Verifying paths and generating API Documentation Markdown..."
          # Check paths
          if [ -f wiki/swagger-ui-bundle.js ] && [ -f wiki/swagger-ui-standalone-preset.js ] && [ -f wiki/openapi.json ]; then
            echo "All required files are in place."
            # Generate Markdown file
            echo "# API Documentation" > wiki/API-Documentation.md
            echo '<div id="swagger-ui"></div><script src="swagger-ui-bundle.js"></script><script src="swagger-ui-standalone-preset.js"></script><script>window.onload = function() { window.ui = SwaggerUIBundle({ url: "openapi.json", dom_id: "#swagger-ui", presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset], layout: "StandaloneLayout" }); }</script>' >> wiki/API-Documentation.md
          else
            echo "Required files are missing."
            exit 1
          fi
          cat wiki/API-Documentation.md  # Output the generated API-Documentation.md

      - name: Update Sidebar
        run: |
          echo "Updating _Sidebar.md..."
          if ! grep -q "## API Documentation" wiki/_Sidebar.md; then
            echo "## API Documentation" >> wiki/_Sidebar.md
          fi
          if ! grep -q "* [API Documentation](API-Documentation.md)" wiki/_Sidebar.md; then
            echo "* [API Documentation](API-Documentation.md)" >> wiki/_Sidebar.md
          fi
          cat wiki/_Sidebar.md  # Output the updated _Sidebar.md

      - name: Commit and Push Changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki documentation from main repository" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: List files in wiki directory after push
        run: ls -la wiki
