name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Redoc CLI
        run: npm install -g @redocly/cli

      - name: Generate API Documentation
        run: |
          redocly build-docs docs/openapi.yaml -o docs/api.html

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Copy Documentation to Wiki
        run: |
          cp docs/api.html wiki/API_Documentation.html
          cp docs/introduction.md wiki/Home.md
          cd wiki
          git add .
          git commit -m "Update wiki documentation from main repository"
          git push
